name: Delete

on:
  delete:
    branches: ["*"]

jobs:
   delete:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4

        - name: Delete branch deploy
          uses: ./.github/actions/delete
          with:
            scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
            scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
